### ISSUE TITLE
JsonException when restoring object state

### ISSUE THREAD

**Issue by grchis** [RocketChat/Rocket.Chat.Java.SDK#19]
When saving the object state, as described in the specs: `    String state=room.toString();
    saveToFile("filename.txt",state);`

the follwing exception is throwned:
`org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONObject.<init>(JSONObject.java:194)
	at org.json.JSONObject.<init>(JSONObject.java:321)
	at io.rocketchat.livechat.LiveChatAPI$ChatRoom.<init>(LiveChatAPI.java:240)
	at hello.chat.ChatService.onInitialData(ChatService.java:132)
	at io.rocketchat.livechat.middleware.LiveChatMiddleware.processCallback(LiveChatMiddleware.java:48)
	at io.rocketchat.livechat.LiveChatAPI.onTextMessage(LiveChatAPI.java:176)
	at io.rocketchat.common.network.Socket$1.onTextMessage(Socket.java:112)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:963)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:746)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)`

The `room.toString()` result looks lie this: `ChatRoom{userName='guest-25', roomId='1jxze8nc7hs8h', userId='QciLCvpuMq2ZbimBb', visitorToken='-163d29c2d06bf5a4dc1915b4d9e34eeb', authToken='1LfwFzKYgsM3nphcV0EeY3jfnsp-9qBe6oPhRy01gtI'}`, but it should look like this:
`{userName='guest-25', roomId='1jxze8nc7hs8h', userId='QciLCvpuMq2ZbimBb', visitorToken='-163d29c2d06bf5a4dc1915b4d9e34eeb', authToken='1LfwFzKYgsM3nphcV0EeY3jfnsp-9qBe6oPhRy01gtI'}`, in order to be successfully deserialized

**Comment by grchis** [comment]
This issue was not reproduced, only after this fix was applied: https://github.com/RocketChat/Rocket.Chat.Java.SDK/issues/18

**Comment by sacOO7** [comment]
Yeah I know. Actually the code got changed while merging PR from another contributor. I will change it right away :+1:

**Comment by sacOO7** [comment]
Please let me know if there are any other errors :)

**Comment by sacOO7** [comment]
You can see old code here :p .

https://github.com/sacOO7/Rocket.Chat.Java.SDK/blob/feature/LiveChatSDK/src/main/java/io/rocketchat/livechat/LiveChatAPI.java

**Comment by sacOO7** [comment]
Use 

`compile 'io.rocketchat:rocketchatjavasdk:0.6.4`

**Comment by sacOO7** [comment]
More issues are welcome :)
